version: '3.8'  # You can specify the version as needed

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's different
    ports:
      - "3000:3000"  # Map the port used by the frontend app
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}  # Pass the MongoDB URI if needed
    volumes:
      - ./frontend/src:/app/src  # Optional: Hot reload during development
      - ./frontend/public:/app/public  # Optional: Hot reload during development
    depends_on:
      - backend  # Ensure backend service is started first

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's different
    ports:
      - "5000:5000"  # Map the port used by the backend API
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}  # Pass the MongoDB URI if needed
    volumes:
      - ./backend:/app  # Optional: Mount backend code for development

networks:
  default:
    driver: bridge  # You can customize the network if needed
